# Generated by Django 4.2.6 on 2023-10-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('cooking_time', models.IntegerField(help_text='in minutes')),
                ('ingredients', models.CharField(help_text='Ingredients must be seperated by commas.', max_length=400)),
                ('difficulty', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
    ]
